### ISSUE TITLE
Intermittent issues in timed command in GUI rule

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab-jruby#525]
I was just playing around with GUI rules to see if openhab-jruby library can be used. It seems that the timed command failed intermittently

Here's my gui rule:
```yaml
configuration: {}
triggers:
  - id: "1"
    configuration:
      itemName: SwitchItem1
      command: ON
    type: core.ItemCommandTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/x-ruby
      script: |-
        require 'openhab'
        SwitchItem2.on for: 2.seconds
    type: script.ScriptAction
```

When I sent a command SwitchItem1 ON, SwitchItem2 will receive a command ON as well. The intermittent part is that SwitchItem2 doesn't always receive a command OFF after 2 seconds - sometimes it does, sometimes it doesn't.
